version: '2'

services:
  postgres:
    image: ${IMG}
    build:
      context: .
      args:
        # https://elasticsearch-py.readthedocs.io/en/master/#compatibility
        - elasticsearch_pip_install_string
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      # opt-out of elastic's xpack
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
      - xpack.security.enabled=false
    ports:
      - 9200:9200
